services:

  #  Postgres
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: book-tracker-api
    healthcheck:
      # We need to pass the user and database argument (user follows "-U" param and db follows "-d" param):
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "book-tracker-api"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #  This app
  book-tracker-api:
    depends_on:
      postgres-db:
        condition: service_healthy
    image: ivangorbunovv/book-tracker-api
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:postgresql://postgres-db:5432/book-tracker-api",
          "security.jwt.secretKey" : "newSecretKey-newSecretKey-newSecretKey"
      }'

volumes:
  postgres-data:
    driver: local
