spring:
  application:
    name: book-tracker-api

  datasource:
    url: jdbc:postgresql://localhost:5432/book-tracker-api
    password: root
    username: postgres
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
security:
  jwt:
    requestHeader: authorization
    secretKey: mySecretKey-mySecretKey-mySecretKey
    validity: 3600 # in seconds
  default-users:
    admin:
      username: admin
      password: admin
