-- Authors
CREATE TABLE IF NOT EXISTS authors (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       name VARCHAR(255) NOT NULL,
                                       PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS authors ADD CONSTRAINT U_authors_name UNIQUE (name);

-- Categories
CREATE TABLE IF NOT EXISTS categories (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                     name VARCHAR(500) NOT NULL,
                                     PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS categories ADD CONSTRAINT U_categories_name UNIQUE (name);

-- Books
CREATE TABLE IF NOT EXISTS books (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     title VARCHAR(500) NOT NULL,
                                     published_at date NOT NULL,
                                     total_pages INTEGER NOT NULL,
                                     added_at timestamp(6) NOT NULL,
                                     PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS books ADD CONSTRAINT U_books_title_published_at UNIQUE (title, published_at);

-- Many-to-many relationships between books and authors
CREATE TABLE IF NOT EXISTS books_authors (
                                     book_id BIGINT NOT NULL,
                                     author_id BIGINT NOT NULL
);

ALTER TABLE IF EXISTS books_authors ADD CONSTRAINT FK_books_authors_book_id FOREIGN KEY (book_id) REFERENCES books;
ALTER TABLE IF EXISTS books_authors ADD CONSTRAINT FK_books_authors_author_id FOREIGN KEY (author_id) REFERENCES authors;

-- Many-to-many relationships between books and categories
CREATE TABLE IF NOT EXISTS books_categories (
                                     book_id BIGINT NOT NULL,
                                     category_id INTEGER NOT NULL
);

ALTER TABLE IF EXISTS books_categories ADD CONSTRAINT FK_books_categories_book_id FOREIGN KEY (book_id) REFERENCES books;
ALTER TABLE IF EXISTS books_categories ADD CONSTRAINT FK_books_categories_category_id FOREIGN KEY (category_id) REFERENCES categories;

