CREATE TABLE IF NOT EXISTS users (
                                       id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                       username VARCHAR(255) NOT NULL,
                                       password VARCHAR(255) NOT NULL,
                                       role varchar(255),
                                       PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS users ADD CONSTRAINT U_users_username UNIQUE (username);
